name: project_doctor
description: Cross-Platoform Health related app

publish_to: 'none'

version: 2.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^7.0.1
  geocoder: 
  flutter_localizations:
    sdk: flutter
  google_maps_flutter: ^2.0.3
  flutter_google_places: ^0.3.0
  firebase_auth: ^1.1.4
  cloud_firestore: ^1.0.2
  firebase_core: ^1.1.1
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.5
  weekday_selector: ^0.4.0
  path_provider: ^2.0.1
  device_preview: ^0.7.1
  url_launcher: ^6.0.2
  easy_localization: ^3.0.0
  stacked_themes: ^0.3.2
  another_flushbar: ^1.10.20
  rounded_loading_button: ^2.0.3
  connectivity: ^3.0.3
  data_connection_checker: ^0.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.8+4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  android : true
  ios: true
  web: true
  background_image: "assets/images/splash/light.png"
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/auth/
    - assets/images/search/
    - assets/translations/
    - assets/map/

  fonts:
    - family: noto_arabic
      fonts:
        - asset: assets/fonts/noto_arabic.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: CustomIcons
      fonts:
      - asset: assets/fonts/CustomIcons.ttf
